-- 5. Bảng Chi tiết Sản phẩm trong Đơn (Order Items)
CREATE TABLE olist_order_items (
    order_id                    VARCHAR2(50) NOT NULL,
    order_item_id               NUMBER(5) NOT NULL,
    product_id                  VARCHAR2(50) NOT NULL,
    seller_id                   VARCHAR2(50) NOT NULL,
    shipping_limit_date         TIMESTAMP,
    price                       NUMBER(10, 2),
    freight_value               NUMBER(10, 2),
    CONSTRAINT pk_olist_order_items PRIMARY KEY (order_id, order_item_id),
    CONSTRAINT fk_items_order FOREIGN KEY (order_id)
        REFERENCES olist_orders (order_id),
    CONSTRAINT fk_items_product FOREIGN KEY (product_id)
        REFERENCES olist_products (product_id),
    CONSTRAINT fk_items_seller FOREIGN KEY (seller_id)
        REFERENCES olist_sellers (seller_id)
);
-- =============================================================================
-- 0. SCHEMA INITIALIZATION (DDL - Chuẩn bị cấu trúc bảng)
-- =============================================================================
CREATE TABLE users (
    user_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR2(50) NOT NULL UNIQUE,
    email       VARCHAR2(100),
    balance     NUMBER(12, 2) DEFAULT 0.00,
    tier        VARCHAR2(20) DEFAULT 'STANDARD',
    status      VARCHAR2(20) DEFAULT 'ACTIVE',
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP
);

-- =============================================================================
-- 1. CREATE (Tạo mới dữ liệu - INSERT / MERGE)
-- =============================================================================

-- 1.1. Insert cơ bản 1 bản ghi
INSERT INTO users (username, email, balance, status)
VALUES ('alice', 'alice@test.com', 250.00, 'ACTIVE');

-- 1.2. Insert nhiều dòng cùng lúc (Oracle Multi-table Insert syntax)
INSERT ALL
    INTO users (username, email, balance, status) VALUES ('bob', 'bob@test.com', 150.00, 'PENDING')
    INTO users (username, email, balance, status) VALUES ('charlie', 'charlie@test.com', 500.00, 'ACTIVE')
SELECT * FROM dual;

-- 1.3. Insert có trả về ID vừa sinh (Dùng nhiều trong PL/SQL Backend)
DECLARE
    v_new_id NUMBER;
BEGIN
    INSERT INTO users (username, email, balance)
    VALUES ('david', 'david@test.com', 100.00)
    RETURNING user_id INTO v_new_id;
    COMMIT;
END;
/

-- 1.4. Bulk Insert từ bảng khác (INSERT INTO ... SELECT)
INSERT INTO users (username, email, balance)
SELECT username, email, balance 
FROM staging_users
WHERE status = 'VALIDATED';


-- =============================================================================
-- 2. READ (Truy vấn dữ liệu - SELECT / FILTER / WINDOW FUNCTION)
-- =============================================================================

-- 2.1. Đọc cơ bản với điều kiện lọc và sắp xếp
SELECT user_id, username, balance, status
FROM users
WHERE status = 'ACTIVE' 
  AND balance >= 100.00
ORDER BY balance DESC;

-- 2.2. Phân trang dữ liệu (Pagination trong Oracle 12c+)
SELECT user_id, username, balance
FROM users
ORDER BY created_at DESC
OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY;

-- 2.3. Đọc dữ liệu kèm logic rẽ nhánh (CASE WHEN)
SELECT 
    username,
    balance,
    CASE 
        WHEN balance >= 500 THEN 'DIAMOND'
        WHEN balance >= 200 THEN 'GOLD'
        ELSE 'SILVER'
    END AS customer_tier
FROM users;

-- 2.4. Đọc kèm Window Functions (Dành cho nghiệp vụ DE / Reporting)
SELECT 
    user_id,
    username,
    status,
    balance,
    -- Tính tổng lũy kế
    SUM(balance) OVER (PARTITION BY status ORDER BY created_at) AS running_balance,
    -- Xếp hạng số dư trong từng nhóm status
    DENSE_RANK() OVER (PARTITION BY status ORDER BY balance DESC) AS balance_rank,
    -- Lấy số dư của giao dịch trước đó
    LAG(balance, 1, 0) OVER (PARTITION BY status ORDER BY created_at) AS prev_balance
FROM users;


-- =============================================================================
-- 3. UPDATE (Cập nhật dữ liệu - UPDATE / MERGE / UPSERT)
-- =============================================================================

-- 3.1. Update cơ bản theo điều kiện
UPDATE users
SET balance = balance + 50.00,
    updated_at = CURRENT_TIMESTAMP
WHERE user_id = 1;

-- 3.2. Update có điều kiện phức tạp (CASE WHEN)
UPDATE users
SET tier = CASE 
        WHEN balance >= 500 THEN 'VIP'
        ELSE 'STANDARD'
    END,
    updated_at = CURRENT_TIMESTAMP
WHERE status = 'ACTIVE';

-- 3.3. Update từ một bảng khác (Correlated Subquery)
UPDATE users u
SET u.email = (SELECT s.email FROM staging_users s WHERE s.user_id = u.user_id)
WHERE EXISTS (SELECT 1 FROM staging_users s WHERE s.user_id = u.user_id);

-- 3.4. UPSERT (MERGE Statement - Thao tác DE kinh điển: Có thì Update, Chưa có thì Insert)
MERGE INTO users t
USING staging_users s
ON (t.user_id = s.user_id)
WHEN MATCHED THEN
    UPDATE SET 
        t.balance = s.balance,
        t.status = s.status,
        t.updated_at = CURRENT_TIMESTAMP
WHEN NOT MATCHED THEN
    INSERT (username, email, balance, status)
    VALUES (s.username, s.email, s.balance, s.status);


-- =============================================================================
-- 4. DELETE (Xóa dữ liệu - DELETE / TRUNCATE / SOFT DELETE)
-- =============================================================================

-- 4.1. Hard Delete (Xóa hẳn dữ liệu theo điều kiện)
DELETE FROM users
WHERE status = 'BANNED' 
  AND created_at < ADD_MONTHS(SYSDATE, -12);

-- 4.2. Xóa dữ liệu trùng lặp (Deduplication dùng ROWID & Analytic Functions)
DELETE FROM users
WHERE ROWID IN (
    SELECT rid FROM (
        SELECT ROWID AS rid,
               ROW_NUMBER() OVER (PARTITION BY email ORDER BY created_at DESC) AS rn
        FROM users
    ) WHERE rn > 1
);

-- 4.3. Soft Delete (Quy chuẩn Production: Đánh dấu trạng thái thay vì xóa vật lý)
UPDATE users
SET status = 'DELETED',
    updated_at = CURRENT_TIMESTAMP
WHERE user_id = 101;

-- 4.4. Truncate (Xóa trắng toàn bộ bảng và reset HWM, không ghi log redo chi tiết)
-- TRUNCATE TABLE staging_users;

-- =============================================================================
-- 5. TRANSACTION CONTROL
-- =============================================================================
COMMIT;    -- Lưu thay đổi
-- ROLLBACK;  -- Khôi phục nếu có lỗi
