-- Tiêu đề: Bài tập Subquery
-- bai1
SELECT 
t.NAME ,t.MILLISECONDS 
FROM TRACK t 
WHERE t.MILLISECONDS >(
SELECT avg(t2.MILLISECONDS )
FROM TRACK t2 
);
-- bai2
SELECT 
t.TRACKID ,t.NAME ,t.UNITPRICE 
FROM TRACK t 
WHERE t.GENREID in (
SELECT
g.GENREID
FROM GENRE g 
WHERE g.NAME IN ('Rock','Jazz')
);
-- bai3
SELECT 
c.CUSTOMERID ,c.COUNTRY ,c.FIRSTNAME ||' '|| c.LASTNAME AS full_name
FROM CUSTOMER c 
WHERE c.COUNTRY IN(
SELECT distinct
e.COUNTRY 
FROM EMPLOYEE e
WHERE c.COUNTRY IS NOT NULL   
);
-- bai4
SELECT 
a.ALBUMID ,a.TITLE 
FROM ALBUM a 
WHERE a.ALBUMID =(
SELECT
t.ALBUMID   
FROM TRACK t
GROUP BY t.ALBUMID 
ORDER BY sum(t.UNITPRICE ) DESC
FETCH FIRST 1 ROWS only
);
-- bai5
SELECT
c.CUSTOMERID ,c.FIRSTNAME ,c.LASTNAME 
FROM customer c
WHERE c.CUSTOMERID NOT IN (
SELECT 
i.CUSTOMERID 
FROM INVOICE i
JOIN INVOICELINE i2 ON i2.INVOICEID =i.INVOICEID 
JOIN track t ON i2.TRACKID =t.TRACKID 
JOIN MEDIATYPE m ON t.MEDIATYPEID = m.MEDIATYPEID 
WHERE m.NAME IN ('MPEG audio file')
);
-- bai6
SELECT ArtistId, Name 
FROM Artist a 
WHERE NOT EXISTS (
    SELECT 1 
    FROM Album al 
    WHERE al.ArtistId = a.ArtistId
);
-- bai7
SELECT t.TRACKID ,t.NAME ,t.ALBUMID ,t.MILLISECONDS  
FROM TRACK t 
WHERE t.MILLISECONDS = (
SELECT
MAX(t2.MILLISECONDS) 
FROM TRACK t2 
WHERE t.ALBUMID  = t2.ALBUMID
);
-- bai8
SELECT 
g.NAME 
FROM GENRE g 
WHERE g.GENREID = (
SELECT 
t.GENREID 
FROM TRACK t
JOIN INVOICELINE i ON i.TRACKID = t.TRACKID 
GROUP BY t.GENREID 
ORDER BY sum(i.UNITPRICE * i.QUANTITY ) DESC 
FETCH FIRST 1 ROWS only
);
-- bai9
SELECT 
e.EMPLOYEEID ,e.FIRSTNAME ,e.LASTNAME 
FROM EMPLOYEE e 
WHERE EXISTS(
SELECT 1 
FROM CUSTOMER c
WHERE c.SUPPORTREPID = e.EMPLOYEEID 
AND c.COUNTRY ='USA'
AND EXISTS (
SELECT 1 
FROM INVOICE i
WHERE i.CUSTOMERID = c.CUSTOMERID 
AND i.TOTAL >10
)
);
WITH avgprice AS (
SELECT avg(t.UNITPRICE ) AS avg
FROM TRACK t 
)
SELECT t.TRACKID ,t.NAME ,t.UNITPRICE 
FROM TRACK t , avgprice a
WHERE t.UNITPRICE > a.avg;
-- bai2
WITH USAcustomer AS (
SELECT c.CUSTOMERID ,c.FIRSTNAME ,c.LASTNAME  FROM CUSTOMER c 
WHERE c.COUNTRY = 'USA'
),
customerspending as(
SELECT uc.CUSTOMERID ,uc.FIRSTNAME ,uc.LASTNAME ,sum(i.TOTAL ) AS total FROM USAcustomer uc
JOIN INVOICE i ON i.CUSTOMERID = uc.CUSTOMERID 
GROUP BY uc.CUSTOMERID , uc.FIRSTNAME ,uc.LASTNAME 
)
SELECT CUSTOMERID ,FIRSTNAME ,LASTNAME ,TOTAL  FROM customerspending 
ORDER BY TOTAL DESC 
FETCH FIRST 3 ROWS ONLY;
-- bai3
WITH genreavgprice AS (
SELECT GENREID ,avg(UNITPRICE) AS avg  FROM track
GROUP BY GENREID 
)
SELECT t.GENREID ,t.ALBUMID ,t.NAME ,t.UNITPRICE   FROM TRACK t 
JOIN genreavgprice g ON g.GENREID = t.GENREID 
WHERE t.UNITPRICE > g.AVG ;
--bai4
WITH customerspending AS (
SELECT CUSTOMERID  ,sum(TOTAL) AS total  FROM INVOICE  
GROUP BY CUSTOMERID 
),
overallavg AS (
SELECT avg(TOTAL ) AS avg FROM customerspending  
)
SELECT c.CUSTOMERID ,c.FIRSTNAME ,c.LASTNAME, cs.TOTAL 
FROM customerspending cs
JOIN CUSTOMER c ON c.CUSTOMERID  = cs.CUSTOMERID
CROSS JOIN overallavg oa 
WHERE cs.TOTAL > oa.AVG 
ORDER BY cs.TOTAL DESC;
-- bai 5
WITH albumstat AS ( 
SELECT ALBUMID ,avg(UNITPRICE ) AS avgalb FROM track
WHERE ALBUMID IS NOT NULL 
GROUP BY ALBUMID 
)
SELECT t.TRACKID ,t.NAME ,ast.AVGALB   FROM TRACK t 
JOIN albumstat ast ON ast.ALBUMID = t.ALBUMID 
FETCH FIRST 10 ROWS ONLY;
-- bai 6
WITH value2011 AS  (
SELECT CUSTOMERID   FROM invoice
WHERE EXTRACT(YEAR FROM INVOICEDATE) = 2011
GROUP BY CUSTOMERID 
HAVING (SUM(TOTAL )) > 40
),
supportemployee AS (
SELECT c.SUPPORTREPID  FROM CUSTOMER c 
JOIN value2011 v ON v.CUSTOMERID = c.CUSTOMERID 
WHERE c.SUPPORTREPID IS NOT NULL 
)
SELECT e.EMPLOYEEID ,e.FIRSTNAME ,e.LASTNAME  FROM EMPLOYEE e 
JOIN supportemployee se ON se.SUPPORTREPID = e.EMPLOYEEID;

